[package]
name = "dust-soft-2d-base"
version = "0.0.0"
edition = "2021"
publish = false

[features]

[dependencies]
dust-core = { path = "../../../core" }
proc-bitfield = { version = "0.5", features = ["nightly"] }
